-- Tạo database
CREATE DATABASE IF NOT EXISTS job_portal_db;

-- Sử dụng database job_portal_db
USE job_portal_db;

-- Tạo bảng CITY
CREATE TABLE CITY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CityName VARCHAR(45) default NULL
);
CREATE TABLE ROLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(20) UNIQUE NOT NULL
);
-- Tạo bảng User với khóa ngoại tới bảng Role
CREATE TABLE USER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(45) UNIQUE NOT NULL,
    Password VARCHAR(200) NOT NULL,
    RegisterDate DATE DEFAULT NULL,
    UserRole_ID INT,
    IsDeleted BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (UserRole_ID) REFERENCES Role(ID)
);
-- Tạo bảng COMPANY
CREATE TABLE COMPANY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Address VARCHAR(100) NOT NULL,
    City_ID INT,
    Avatar VARCHAR(300) NOT NULL,
    Description VARCHAR(1000),
    Email VARCHAR(45) NOT NULL,
    Ischecked BOOLEAN NOT NULL DEFAULT 0,
    IsDeleted BOOLEAN NOT NULL DEFAULT 0,
    User_ID INT NOT NULL,
    FOREIGN KEY (User_ID) REFERENCES USER(ID),
    FOREIGN KEY (City_ID) REFERENCES CITY(ID)
);

-- Tạo bảng CANDIDATE
CREATE TABLE CANDIDATE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Full_Name VARCHAR(100) default NULL,
    Email VARCHAR(100) default NULL,
    DateOfBirth DATE default NULL,
    City_ID INT default null,
    Avatar VARCHAR(300) default NULL,
    Description VARCHAR(500) default NULL,
    Phone VARCHAR(10) default NULL,
    Degree VARCHAR(45) default NULL,
    Major VARCHAR(45) default NULL,
    Sex VARCHAR(45) default NULL,
    User_ID INT default NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    FOREIGN KEY (User_ID) REFERENCES USER(ID),
    FOREIGN KEY (City_ID) REFERENCES CITY(ID)
);

-- Tạo bảng ADMINISTRATOR
CREATE TABLE ADMINISTRATOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Full_Name VARCHAR(100) default NULL,
    Email VARCHAR(100) default NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    User_ID INT default NULL,
    FOREIGN KEY (User_ID) REFERENCES USER(ID)
);
-- Tạo bảng CANDIDATE_COMPANY
CREATE TABLE CANDIDATE_COMPANY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Candidate_ID INT DEFAULT NULL,
    Company_ID INT DEFAULT NULL,
    FOREIGN KEY (Candidate_ID) REFERENCES CANDIDATE(ID),
    FOREIGN KEY (Company_ID) REFERENCES COMPANY(ID)
);

-- Tạo bảng JOB
CREATE TABLE JOB (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Company_ID INT DEFAULT NULL,
    Name VARCHAR(100) DEFAULT NULL,
    Description VARCHAR(1000) DEFAULT NULL,
    SalaryFrom decimal(20,0) DEFAULT NULL,
    SalaryTo decimal(20,0) DEFAULT NULL,
    AgeFrom INT DEFAULT NULL,
    AgeTo INT DEFAULT NULL,
    EndDate DATE DEFAULT NULL,
    CreateDate DATE DEFAULT NULL,
    Quantity INT DEFAULT NULL,
    IsChecked BOOLEAN DEFAULT 0,
    DegreeRequired VARCHAR(200) NOT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    SexRequired VARCHAR(100) DEFAULT NULL,
    ProbationaryPriod INT DEFAULT NULL,
    Benefit VARCHAR(500) DEFAULT NULL,
    Position VARCHAR(100) DEFAULT NULL,
    Type VARCHAR(100) DEFAULT NULL,
    City_ID INT,
    Address VARCHAR(200) DEFAULT NULL,
    ExperienceRequired INT DEFAULT NULL,
    JobRequired VARCHAR(500) DEFAULT NULL,
    FOREIGN KEY (Company_ID) REFERENCES COMPANY(ID),
    FOREIGN KEY (City_ID) REFERENCES CITY(ID)
);

-- Tạo bảng MAJOR
CREATE TABLE MAJOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) DEFAULT NULL
);

-- Tạo bảng JOB_MAJOR
CREATE TABLE JOB_MAJOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Job_ID INT DEFAULT NULL,
    Major_ID INT DEFAULT NULL,
    Point INT DEFAULT NULL,
    FOREIGN KEY (Job_ID) REFERENCES JOB(ID),
    FOREIGN KEY (Major_ID) REFERENCES MAJOR(ID)
);

-- Tạo bảng CURRICULUM_VITAE
CREATE TABLE CURRICULUM_VITAE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CareerGoals VARCHAR(500) DEFAULT NULL,
    DegreeDetail VARCHAR(500) DEFAULT NULL,
    ExperienceDetail VARCHAR(500) DEFAULT NULL,
    Skill VARCHAR(100) DEFAULT NULL,
    ForeignLanguage VARCHAR(200) DEFAULT NULL,
    Candidate_ID INT DEFAULT NULL,
    CV_Link VARCHAR(100) DEFAULT NULL,
    Is_Deleted BOOLEAN  DEFAULT 0,
    FOREIGN KEY (Candidate_ID) REFERENCES CANDIDATE(ID)
);

-- Tạo bảng CANDIDATE_JOB
CREATE TABLE CANDIDATE_JOB (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Candidate_ID INT DEFAULT NULL,
    Job_ID INT DEFAULT NULL,
    CV_ID INT DEFAULT NULL,
    AppliedDate DATE DEFAULT NULL,
    IsLiked BOOLEAN DEFAULT 0,
    IsApplied BOOLEAN DEFAULT 0,
    FOREIGN KEY (Candidate_ID) REFERENCES CANDIDATE(ID),
    FOREIGN KEY (Job_ID) REFERENCES JOB(ID),
    FOREIGN KEY (CV_ID) REFERENCES CURRICULUM_VITAE(ID)
);

-- Tạo bảng COMMENT
CREATE TABLE COMMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Candidate_ID INT DEFAULT NULL,
    Company_ID INT DEFAULT NULL,
    Rating INT CHECK (Rating >= 0 AND Rating <= 5),
    Assessment VARCHAR(300) DEFAULT NULL,
    CreatedDate DATE DEFAULT NULL,
    FOREIGN KEY (Candidate_ID) REFERENCES CANDIDATE(ID),
    FOREIGN KEY (Company_ID) REFERENCES COMPANY(ID)
);






-- Thêm dữ liệu cho bảng CITY
INSERT INTO CITY (CityName) VALUES ('Hà Nội');
INSERT INTO CITY (CityName) VALUES ('Hồ Chí Minh');
INSERT INTO CITY (CityName) VALUES ('Đà Nẵng');


-- Thêm dữ liệu cho bảng ROLE
INSERT INTO ROLE (Name) VALUES ('Admin');
INSERT INTO ROLE (Name) VALUES ('Company');
INSERT INTO ROLE (Name) VALUES ('Candidate');


INSERT INTO `user` VALUES (1,'ADMIN','$2a$10$mvp39XVap64nUs1uHrhDZ.R6euukbZuZlM9HYI5XJR2vjzxYux3Em',NULL,'1',0);
INSERT INTO `ADMINISTRATOR` VALUES (1,'nnhatsang','nhatsang@gmail.com',0,'1');

